[android]
package_name = "dev.mineplay.agent"
minecraft_package_name = "com.mojang.minecraftpe"
min_sdk = 29
prefer_wireless_debugging = true

[network]
transport = "quic"
listen_port = 47651
pairing_timeout_seconds = 60

[video]
preferred_width = 1920
preferred_height = 1080
target_fps = 60
target_bitrate_kbps = 20000

[fallback]
allow_accessibility_fallback = true
allow_shell_mode = true

[playback]
backend = "scrcpy"
fullscreen = true
borderless = true
fill_mode = "auto"
dynamic_display = true
prefer_virtual_display = true
virtual_display_hide_system_decorations = true
virtual_display_preserve_content = true
target_aspect_width = 16
target_aspect_height = 9
no_audio = true
stay_awake = true
prefer_hid_keyboard = true
prefer_hid_mouse = true
auto_launch_minecraft = true

[diagnostics]
enable_session_perf_log = false
enable_scrcpy_fps_counter = false
enable_adb_rtt_probe = false
compare_previous_perf = true
adb_rtt_probe_interval_ms = 1000
adb_rtt_probe_timeout_ms = 1500

[scrcpy]
auto_install = true
video_codec = "h264"
video_codec_options = ""
max_size = 1920
video_buffer_ms = 30
render_driver = "direct3d"
disable_mipmaps = true
disable_clipboard_autosync = true
verbosity = "info"
turn_screen_off = true
